import type { LocalModel } from "./types";

export const localModels: LocalModel[] = [
  {
    id: "llama-3.1-8b",
    name: "Llama 3.1 8B Instruct",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
    description:
      "A capable general-purpose model that runs comfortably on consumer hardware and supports a long 128k context window.",
    minRamGb: 8,
    recommendedRamGb: 16,
    minVramGb: null,
    os: ["macos", "windows", "linux"],
    strengths: ["general", "privacy", "writing"],
    tags: ["balanced", "long-context", "easy-to-run"],
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B Instruct",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Llama-3.1-70B-Instruct",
    description:
      "A large, reasoning-capable model for demanding tasks. Needs significant RAM or quantization to run locally.",
    minRamGb: 64,
    recommendedRamGb: 128,
    minVramGb: 48,
    os: ["linux", "windows"],
    strengths: ["coding", "writing", "multimodal"],
    tags: ["high-end", "reasoning", "large"],
  },
  {
    id: "qwen2.5-7b-coder",
    name: "Qwen2.5 Coder 7B",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
    description:
      "A code-specialized model with strong performance on programming benchmarks and a friendly hardware footprint.",
    minRamGb: 8,
    recommendedRamGb: 16,
    minVramGb: null,
    os: ["macos", "windows", "linux"],
    strengths: ["coding", "general"],
    tags: ["code", "fast", "accurate"],
  },
  {
    id: "deepseek-coder-v2-lite",
    name: "DeepSeek-Coder-V2 Lite",
    provider: "DeepSeek",
    url: "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
    description:
      "A 16B MoE coder model that punches above its weight for software-engineering tasks.",
    minRamGb: 16,
    recommendedRamGb: 32,
    minVramGb: 12,
    os: ["linux", "windows"],
    strengths: ["coding"],
    tags: ["moe", "code", "advanced"],
  },
  {
    id: "llava-1.6-mistral",
    name: "LLaVA 1.6 Mistral 7B",
    provider: "LLaVA",
    url: "https://huggingface.co/llava-hf/llava-v1.6-mistral-7b-hf",
    description:
      "A vision-language model that can describe and reason about images alongside text.",
    minRamGb: 16,
    recommendedRamGb: 32,
    minVramGb: 8,
    os: ["linux", "windows", "macos"],
    strengths: ["multimodal", "general"],
    tags: ["vision", "image", "multimodal"],
  },
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "Microsoft",
    url: "https://huggingface.co/microsoft/phi-4",
    description:
      "A compact 14B model with surprisingly strong reasoning and instruction following.",
    minRamGb: 16,
    recommendedRamGb: 24,
    minVramGb: null,
    os: ["windows", "linux", "macos"],
    strengths: ["general", "writing", "coding"],
    tags: ["compact", "reasoning", "efficient"],
  },
  {
    id: "gemma-2-9b",
    name: "Gemma 2 9B",
    provider: "Google",
    url: "https://huggingface.co/google/gemma-2-9b-it",
    description:
      "A lightweight, well-balanced model with strong safety tuning and broad use-case coverage.",
    minRamGb: 8,
    recommendedRamGb: 16,
    minVramGb: null,
    os: ["linux", "windows", "macos"],
    strengths: ["general", "writing", "privacy"],
    tags: ["safe", "balanced", "lightweight"],
  },
  {
    id: "wizardlm-2-7b",
    name: "WizardLM 2 7B",
    provider: "Microsoft",
    url: "https://huggingface.co/microsoft/WizardLM-2-7B",
    description:
      "A conversation-focused model tuned for helpful, nuanced writing and long-form answers.",
    minRamGb: 8,
    recommendedRamGb: 16,
    minVramGb: null,
    os: ["linux", "windows", "macos"],
    strengths: ["writing", "general"],
    tags: ["chat", "writing", "helpful"],
  },
];
